### ISSUE TITLE
KMongo 4.2.7 does not work with Kotlinx Coroutines 1.5

### ISSUE THREAD

**Issue by JonathanxD** [Litote/kmongo#282]
KMongo 4.2.7 is not working with Kotlinx Coroutines 1.5. Since some function signatures have changed, it does throw `NoSuchMethodError` exception.

The current workaround is to exclude Kotlinx Coroutines from `KMongo` dependencies in Gradle, and add newer versions of them:

```groovy
dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.0")
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-reactive:1.5.0'

    implementation("org.litote.kmongo:kmongo-coroutine:4.2.7") {
        exclude group: "org.jetbrains.kotlinx", module: "kotlinx-coroutines-reactive"
        exclude group: "org.jetbrains.kotlinx", module: "kotlinx-coroutines-core-jvm"
    }
}
```

It seems to be working without any issues with Coroutines 1.5.

**Comment by zigzago** [comment]
Thank you for reporting. This is strange, as kmongo 4.2.7 depends of coroutine of 1.5.0-RC as you can see here: https://mvnrepository.com/artifact/org.litote.kmongo/kmongo-coroutine-core/4.2.7 

Anyway I release a new kmongo version today with updated dependencies

**Comment by JonathanxD** [comment]
Thanks for the fix. I'm not sure why this was happening as you've shown that dependencies are correctly set. I've seen Gradle resolve dependencies to lower versions before, in case of conflicts, but I will not dig too much into this as the new release of KMongo (4.2.8) solved the problem.

Thanks again!!
